name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: npm install backend
      run: npm install

    - name: npm install frontend
      run: npm run install:fe

    - name: build frontend
      run: npm run build:ui
    
    - name: deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: murmuring-sierra-69706
        heroku_email: hellsten.antti@gmail.com
        healthcheck: https://murmuring-sierra-69706.herokuapp.com/health
        checkstring: ok
        rollbackonhealthcheckfailed: true